### ISSUE TITLE
Actualizar diseño de la card de las tarjetas

### ISSUE THREAD

**Issue by Michael-Liendo** [Michael-Liendo/todo-list-app#10]
diseño esperado:
![image](https://github.com/Michael-Liendo/todo-list-app/assets/70660410/761bb4e7-73ed-4c15-bfdc-53a655f4c8a0)

por ahora las tarjetas deben de tener un solo color

las tarjetas deben de contener:
- Titulo
- fecha
- descripción

**Comment by daridjcm** [comment]
Puedo implementarlo.
